### ISSUE TITLE
Doesn't work on LG P880 (stock 4.1.2), claims not to be enabled

### ISSUE THREAD

**Issue by IzzySoft** [pvalenta/CompleteActionPlus#1]
I'm using an LG Optimus 4X HD (P880) running stock ROM with JellyBean 4.1.2, the latest _stable_ Xposed. Trying to use the latest stable CompleteActionPlus (2.7.0), I cannot even configure the module: it always claims I've not enabled it or have not yet rebooted. It _is_ enabled (check-mark there), and I've rebooted 2 or 3 times since. Other modules (e.g. _NotificationCount_) work as expected (so it's not a n00b issue on my end).

![modules](https://cloud.githubusercontent.com/assets/6781438/7901901/991cb33a-07a0-11e5-9aa3-ab8e064401ad.jpg) ![error](https://cloud.githubusercontent.com/assets/6781438/7901903/9e53fd36-07a0-11e5-8621-0a1107b8d7eb.jpg)

Any idea what could be wrong there? Should I try an older version of CAP instead (if so, which)?

**Comment by pvalenta** [comment]
Time after time I got such feedbacks. :-(

Some users claim it happen when mod get installed on external card. Some
simply uninstall restart and then fresh install again. Or more one version
back and then back to latest.

Please try.

Pavel

**Comment by IzzySoft** [comment]
Thanks, Pavel!

The external card we can rule out here. But "toggling" I can try, as well as switching to a previous version. I will report back then, but that might take a little: I'm not a fan of "heavy booting" :stuck_out_tongue_winking_eye:

Izzy.

**Comment by IzzySoft** [comment]
OK, due to another issue with Xposed I just had a reboot-orgy … So far I've tried:
- deacivating/activating
- soft boot, device restart
- using v2.6.1

Results always the same. Any more ideas – or am I out of business here? Asking the other way around: What is CAP doing when I open it (from app drawer or from modules list) that could cause this? I've just had an issue with the Xposed Installer causing a reboot when trying to install a module from there, with the only indicator being some server unreachable (see [Crash + soft-reboot when trying to install module via Download tab](https://github.com/rovo89/XposedInstaller/issues/286)), so it might be something strange happening here as well.

**Comment by IzzySoft** [comment]
PS: Meanwhile I tried all other Xposed modules available to deal with the "openWith" dialog, none of them was working. One of them was causing the "crash + soft-reboot" mentioned before, the other simply had no effect (but also no GUI, so I could not verify if that might be the same issue as with your module). Which might indicate something device-specific (modifications done by the manufacturer, as I still run the latest official "stock" ROM from LG). If you have any ideas, I'm open to run a test-build for verification and provide feedback to you.

**Comment by IzzySoft** [comment]
Outdated (my P880 is no longer on 4.1.2 anyway for a long time already – and development of this module stalled anyway). Thanks again for your help, @pvalenta – closing this now for cleanup.
